[package]
name = "dreadnom"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
camino = "1.1.9"
clap = { version = "4.5.23", features = ["derive"] }
logos = "0.15.0"
regex = "1.11.1"

[dev-dependencies]
assert_cmd = "2.0.16"
assert_fs = "1.1.2"
