# based on ci.yml in axodotdev/cargo-dist 
# The "Normal" CI for tests and linters and whatnot
name: Rust CI

# Ci should be run on...
on:
  # Every pull request (will need approval for new contributors)
  pull_request:
  # Every push to...
  push:
    branches:
      # The main branch
      - main
  # And once a month
  # This can catch things like "rust updated and actually regressed something"
  schedule:
    - cron: "11 3 22 * *"

# We want all these checks to fail if they spit out warnings
env:
  RUSTFLAGS: -Dwarnings

jobs:
  # Check that rustfmt is a no-op
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  # Clippy -- the axodotdev clippy section didn't work for me, so I modified
  # the docs section instead
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - uses: swatinem/rust-cache@v2
      - run: cargo clippy --workspace --tests --examples

  # Make sure the docs build without warnings
  docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rust-docs
      - uses: swatinem/rust-cache@v2
      - run: cargo doc --workspace --no-deps

  # Check for typos (exceptions are provided by the typos.toml)
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling of entire workspace
        uses: crate-ci/typos@v1.26.0

  # Build and run tests/doctests/examples on all platforms
  # FIXME: look into `cargo-hack` which lets you more aggressively
  # probe all your features and rust versions (see tracing's ci)
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      # Test the cross-product of these platforms+toolchains
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
        rust: [stable]
    steps:
      # Setup tools
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}
      # Run the tests/doctests (default features)
      # - run: cargo test --workspace
      #  env:
      #    PWD: ${{ env.GITHUB_WORKSPACE }}
      # Run the tests/doctests
      - run: cargo test --workspace
        env:
          PWD: ${{ env.GITHUB_WORKSPACE }}
          CARGO_DIST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Test the examples (default features)
      # - run: cargo test --workspace --examples --bins
      #  env:
      #    PWD: ${{ env.GITHUB_WORKSPACE }}
      # Test the examples
      - run: cargo test --workspace --examples --bins
        env:
          PWD: ${{ env.GITHUB_WORKSPACE }}
